### ISSUE TITLE
Output Tree

### ISSUE THREAD

**Issue by keighrim** [keighrim/hspJapanese#1]
Rather than a almost syntactic parse tree, how about return a table of semantic roles, since we are doing semantic parser.
For example;

"kare ga tokyo kara bosutonn ni ki ta no ha(wa?) kinou des ita ."
[Pred: kuru _(restore dict form)_ 
Subj: kare
Spacial: (from) tokyo (to) bostonn
Temporal: (past) kinou]

It's just an idea. 

We need a few restriction for this, for instance every NP must have a case marking.

**Comment by tcurcuru** [comment]
From the assignment description I assumed we were supposed to be doing a syntactic parser. But I guess if making the VP rule work turns out to be too difficult, this wouldn't be a bad alternative. Would we extract temporal information from the verb and Auxen (e.g. past, progressive, etc.)?

For the current parser I am already assuming every NP has its case marking, and is thus a "Particle Phrase."

**Comment by keighrim** [comment]
closing stale issue
